### ISSUE TITLE
How to visualize the classification results

### ISSUE THREAD

**Issue by tarek-nawara** [tarek-nawara/sentiment-analysis#10]
we need to build a simple visualization board for our classification results.

**Comment by tarek-nawara** [comment]
Started playing with Elasticsearch and Kibana and they seem to be really good candidates.
[
![kibana_test](https://user-images.githubusercontent.com/19335185/35357081-0aef038a-015b-11e8-948f-5b8a8bdae298.png)
](url)

**Comment by tarek-nawara** [comment]
[https://www.elastic.co/guide/en/elasticsearch/hadoop/master/spark.html](url)

**Comment by mohamedramadan2515** [comment]
We don't visualize anything!
