### ISSUE TITLE
Better way of doing the sentiment analysis

### ISSUE THREAD

**Issue by tarek-nawara** [tarek-nawara/sentiment-analysis#12]
Started playing with [apacheNLP](http://opennlp.apache.org/) as a candidate, other candidates are:
- Google natural language API.
- [Stanford NER library](https://nlp.stanford.edu/software/CRF-NER.shtml)

**Comment by tarek-nawara** [comment]
Most of them need labeled data, started playing with python `textblob` library for labeling.

**Comment by tarek-nawara** [comment]
Managed to reduce the testing error to: 0.045081967213114756, after labeling the training data using python 'textblob' library.

![test_error_reduced](https://user-images.githubusercontent.com/19335185/35578203-0c3bc3b4-05ec-11e8-82fb-bad191090ec5.png)

**Comment by tarek-nawara** [comment]
python `textblob` library is classifying correctly.

![correct_record](https://user-images.githubusercontent.com/19335185/35579512-8278ca24-05ef-11e8-9e47-ddb0fe107f1d.png)

**Comment by mohamedramadan2515** [comment]
How you managed to reduce the testing error?
Do you use the same data in our resources or you will create new data from twitter stream? 
Will you use our model with new labeled data or you want to substitute it with this one?

**Comment by tarek-nawara** [comment]
I use the same model with the same data we have. the only difference is that we use python's `textblob` library to label the data instead of labeling it naively based on certain keywords and then feed the labeled tweets to the same model as we did before.

We can find more about `textblob` here:
[TextBlob](http://textblob.readthedocs.io/en/dev/)

**Comment by mohamedramadan2515** [comment]
Why don't we use textblob directly as a model?

**Comment by tarek-nawara** [comment]
Good question, I think it will be hard because this is a python library and we can't access it from our code in a clean way. Unfortunately, there isn't any equivalent thing for it running on the JVM. but I think it is a good thing that we build a model ourselves, it seems a good task we can talk about.
