### ISSUE TITLE
Must remove emojes and all non ascii character from tweet text given by the stream before classifying it

### ISSUE THREAD

**Issue by tarek-nawara** [tarek-nawara/sentiment-analysis#13]

**Comment by mohamedramadan2515** [comment]
Can you add a description why we should do this?

**Comment by tarek-nawara** [comment]
Sure  imagine that we have something like this  😪 in the tweet body, this can be one of these in `UTF-8` representation.`0xF0`, `0x9F`, `0x98`, `0xAA`. this will corrupt our model as it may use them as features to classify based on. the problem that they have different representation over the tweets. I'm still not sure what is the right thing to do here.

**Comment by mohamedramadan2515** [comment]
I don't know but I think emoji reflect a very good intuition to know if this is a happy or sad tweet.

**Comment by tarek-nawara** [comment]
I totally agree, I just mentioned it to point out the multiple representations problem.

**Comment by tarek-nawara** [comment]
Added them again to the labeled tweets, only removed the `URLs` and the mentions in the tweet messages. we need to see if they will help to improve the classification accuracy.

**Comment by tarek-nawara** [comment]
we are removing mentions and external links from the tweet text.
