### ISSUE TITLE
Aggregation on tweets location problem

### ISSUE THREAD

**Issue by mohamedramadan2515** [tarek-nawara/sentiment-analysis#19]
https://developer.twitter.com/en/docs/tutorials/filtering-tweets-by-location

We need to make any visualization between location and number of happy or sad

**Comment by tarek-nawara** [comment]
we can add the `GeoLocation` of the tweet as a field of the classified tweet.

**Comment by sherif98** [comment]
![map_tweets](https://user-images.githubusercontent.com/13878518/36921392-e32a8caa-1e6c-11e8-8244-0759b5ec9bad.png)

**Comment by sherif98** [comment]
The more the dot is red colored the more is happy.

**Comment by MohamedElhawaty** [comment]
That's really cool 👍

**Comment by tarek-nawara** [comment]
Nice work :+1:

**Comment by mohamedramadan2515** [comment]
wow (y)
