### ISSUE TITLE
Visualization for misclassified  tweets in training and testing data

### ISSUE THREAD

**Issue by mohamedramadan2515** [tarek-nawara/sentiment-analysis#20]
I don't know how we will make aggregation on those tweets because now all the training data we have didn't have a location parameter, so I think those are two problems finding training data with something we can aggregate about and we need to add those data in separate dataset on elasticsearch then add another visualization of those data in kibana

**Comment by tarek-nawara** [comment]
model evaluation works as before but separated in a different class now.

![image](https://user-images.githubusercontent.com/19335185/36920067-3136ab5e-1e68-11e8-82bc-90aaad67bbc9.png)
