### ISSUE TITLE
Passing the  NN model to Spark

### ISSUE THREAD

**Issue by MohamedElhawaty** [tarek-nawara/sentiment-analysis#27]
Passing the NN model that uses Google word2vec model to Spark throws an OutofMemory exception. The size of the word2vec model is almost 4GB and Spark needs extra 4GB as it serializes the model and creates another instance of it that is going to be used on the executor node (the same machine on our case).

**Comment by tarek-nawara** [comment]
we need to change the way we perform model evaluation
