### ISSUE TITLE
Some tweets return null when trying to access its text

### ISSUE THREAD

**Issue by MohamedElhawaty** [tarek-nawara/sentiment-analysis#31]
Some of the tweets in the training [data](http://help.sentiment140.com/for-students/) return null when trying to access its text in the DataIterator class. It might be related to the way we convert the data to JSON files as replacing '\' with '\\' solves the problems for some tweets.

**Comment by tarek-nawara** [comment]
Any progress on this one. we discussed that the `TweetsLoader` can support loading `csv` files in addition to `Json`

**Comment by MohamedElhawaty** [comment]
Should be fixed by pull request #65 as we are using Jackson to write the JSON file, we close it later after we double check it.
