### ISSUE TITLE
SpellingService Bug

### ISSUE THREAD

**Issue by tarek-nawara** [tarek-nawara/sentiment-analysis#63]
Imagin the following:

original String: `hav a god day`
the replacements would be a: `hav` -> `have`, and `god` -> `good`.
no replacement would fail because the matches would have `from` and `to` according to the original message so replacements would have ranges: [0, 2] [6,8]
if you replace in the string builder the first replacement would yield:
`have a god day` then trying to do the second replacement would go to a wrong index.

**Comment by MohamedElhawaty** [comment]
Done 😎 🔥 😎
